version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    command: supervisord -c supervisord.conf
    restart: on-failure

  redis:
    image: redis
    volumes:
           - ./redis.conf:/usr/local/etc/redis/redis.conf
           - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=auth_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  redis_data: