# Generated by Django 5.0 on 2023-12-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='laptop_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
