# Generated by Django 5.0 on 2023-12-24 21:00

import product_questions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_questions', '0002_alter_comment_laptop_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(product_questions.models.get_deleted_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
