# Generated by Django 5.0.1 on 2024-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_questions', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='laptop_id',
            field=models.CharField(max_length=24),
        ),
    ]
