# Generated by Django 5.0.1 on 2024-01-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_questions', '0004_alter_comment_laptop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='laptop_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
