# Generated by Django 5.0.1 on 2024-01-08 20:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='saved_laptops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=24), size=None),
        ),
    ]
